# Base config to merge into
# If an absolute path is given then it is used
# Otherwise it is assumed to me reative to the directory of this file
base: "ACT0012_base.yaml"
noise_map: True
model_map: True
# Cluster name
# Used both for the output path as well as to load presets
name: ""
sim: False # If True use TODs to make noise and add a simulated cluster

# Define the model
# Define the model
model:
  # Unit conversion to apply at the end
  # Will be evaled
  unit_conversion: "float(wu.get_da(constants['z'])*wu.y2K_RJ(constants['freq'], constants['Te'])*wu.XMpc/wu.me)"
  # Structure to include in the model
  structures:  
    cl1:
      structure: "gnfw"
      parameters:
        dx_1:
          value: -67.2
        dy_1:
          value: 52.0
        dz_1:
          value: 0.0
        rx_1:
          value: 52.7
        ry_1:
          value: 52.7
        rz_1:
          value: 52.7
        theta:
          value: 0.0
        P0:
          value: 8.403
        c500:
          value: 1.177
        m500:
          value: "1.22e14"
          to_fit: True
        gamma:
          value: .3081
        alpha:
          value: 1.0510
        beta:
          value: 4.8273
        z:
          value: 0.337661
    cl2:
      structure: "gnfw"
      parameters:
        dx_2:
          #RA=3.2394 deg, dx=0.0194 deg
          value: 68.1
        dy_2:
          #dec=-8.9741 deg, dy= -0.0241 deg
          value: -50.1
        dz_2:
          value: 0.0
        rx_2:
          value: 44.8
        ry_2:
          value: 44.8
        rz_2:
          value: 44.8
        theta :
          value: 0.0
        P0 :
          value: 8.403
        c500 :
          value: 1.177
          #from Planck Collaboration V 2013
        m500 :
          value: "9.68e13"
          to_fit: True
        gamma :
          value: 0.3081
        alpha :
          value: 1.0510
        beta :
          value: 4.7256
        z :
          value: 0.35200
    cylindrical_beta:
      structure: "cylindrical_beta"
      parameters:
        dx:
          #RA=3.21deg, dx=-0.01 deg
          value: 0.45
        dy:
          #RA=-8.95 deg, dy=0 deg
          value: 1.0
        dz:
          value: 0.0
        L:
          #0.02 deg
          value: 50.
          to_fit: False
        theta:
          value: -0.635
          to_fit: False
          #parameter from xray code
        P0:
          value: 0.005
          to_fit: True
        r_c:
          #0.013 deg
          value: 20.
          to_fit: True
          priors: [0.0, 10000.]
        beta:
          value: 1.3333
          to_fit: False
          priors: [0.5, 10.0]
    ps_gaussian_n:
      structure: "gaussian"
      parameters:
          dx:
            #RA=3.2048 deg, dx=-0.0152 deg
            value: -52.
            to_fit: True
          dy:
            #dec= -8.9584 deg, dy=-0.0084 deg
            value: -62.
            to_fit: True
          sigma:
            #0.005 deg
            value: 8.
            to_fit: True
            priors: [2., 10.]
          amp:
            value: 0.006569
            #0.0093 K -> converto dividendo per 1.41556 K/Jy/beam -> 0.006569 Jy/beam
            to_fit: True
            priors: [0.001, 0.02]
