# Base config to merge into
# If an absolute path is given then it is used
# Otherwise it is assumed to me reative to the directory of this file
base: "base_unit.yaml"

# Cluster name
# Used both for the output path as well as to load presets
name: "SIM_ACT0328-2140"
sim: True # If True use TODs to make noise and add a simulated cluster

# Define the model
model:
  # Unit conversion to apply at the end
  # Will be evaled
  unit_conversion: "float(wu.get_da(constants['z'])*wu.y2K_RJ(constants['freq'], constants['Te'])*wu.XMpc/wu.me)"
  # Structure to include in the model
  structures:
    # Name of the first structure
    cluster1:
      structure: "isobeta"
      parameters:

    cyl:
      structure: "cylindrical" # What type of structure it is
      # Parameters for the structure
      parameters:
        dx_1: # Name of the first parameter
          value: 0.0 # Value to use/start at, will be evaled
        dy_1:
          value: 0.0
        dz_1:
          value: 0.0
        L:
          value: 100 
        theta:
          value: 0.0
        P0:
          value: 1. 
        r_c:
          value: 20.
        beta:
          value: 5.4905 


