cluster:
  name: "MOOJ2354"
  Te: 5.0
  freq: 90e9
paths:
  tods: "/scratch/r/rbond/jorlo/M2-TODs/MOOJ2354"
  glob: "Signal_TOD*.fits"
  ndo: False
  odo: False
  outroot: "/scratch/r/rbond/jorlo/Reductions"
  subdir: "MOOJ2354_A10"
coords:
  z: 0.97 
  r_map: "3.0*60"
  dr: "1.0"
  x0: "(358.687185*u.degree).to(u.radian).value"
  y0: "(35.1253979*u.degree).to(u.radian).value"  
  conv_factor: "(180 * 3600) / np.pi"
beam:
  fwhm1: "9.735"
  amp1: 0.9808
  fwhm2: "32.627"
  amp2: 0.0192
bowling:
  sub_poly: False 
  method: "pred2"
  degree: 5
minkasi:
  noise:
    class: "minkasi.NoiseSmoothedSVD"
    args: "[]"
    kwargs: "{'fwhm':10}"
  maxiter: 10
  npass: 5
  dograd: False
sim: True
models:
  a10:
    func: "partial(helper, xyz=xyz, dx=float(da*y2K_RJ(freq, Te)*dr*XMpc/me), beam=beam, argnums=np.where(_to_fit)[0], n_a10=1)"
    parameters:
      dx_1:
        value: 0.0 
        to_fit: False
      dy_1:
        value: 0.0
        to_fit: False 
      dz_1:
        value: 0.0 
        to_fit: False
      theta:
        value: 0.0
        to_fit: False    
      P0:
        value: 8.403
        to_fit: False
      c500:
        value: 1.177 
        to_fit: False 
      m500:
        value: "2.5e14"
        to_fit: True 
      gamma:
        value: .3081 
        to_fit: False 
        #priors:
        #  type: "flat"
        #  value: "[0.0, 10.0]"
      alpha:
        value: 1.051 
        to_fit: False
      beta:
        value: 5.4905 
        to_fit: False
      z:
        value: 0.97 
        to_fit: False
      #sx:
      #  value: 0.0
      #  to_fit: False
      #sy:
      #  value: 0.0
      #  to_fit: False
      #sz:
      #  value: 0.0
      #  to_fit: False 
      #sr_1:
      #  value: ".320/da"
      #  to_fit: False
      #sr_2:
      #  value: ".320/da"
      #  to_fit: False
      #sr_3:
      #  value: ".320/da"
      #  to_fit: False
      #s_theta:
      #  value: "np.deg2rad(97)"
      #  to_fit: False
      #shock_val:
      #  value: .26
      #  to_fit: True 
      
