base: "base_sampler.yaml"
name: "RXJ1347"
sim: True
model:
  unit_conversion: "float(mju.get_da(constants['z'])*mju.y2K_RJ(constants['freq'], constants['Te'])*mju.XMpc/mju.me)"
  structures:
    ps_gauss:
      structure: "gaussian"
      parameters:
        dx_g:
          value: 0.0
          to_fit: True
        dy_g:
          value: 0.0
          to_fit: True 
        sigma:
          value: 4
        amp_g:
          value: 0.2
          to_fit: True 
