cluster:
  name: "MS0735"
  Te: 5.0
  freq: 90e9
paths:
  tods: "/scratch/r/rbond/jorlo/MS0735/TS_EaCMS0f0_51_5_Oct_2021"
  glob: "Signal_TOD*.fits"
  ndo: False
  odo: False
  outroot: "/scratch/r/rbond/jorlo/Reductions"
  subdir: "r3=r1"
coords:
  z: .216
  r_map: "3.0*60*da"
  dr: ".5*da"
  x0: "Angle('07 41 44.5 hours').to(u.radian).value"
  y0: "Angle('74:14:38.7 degrees').to(u.radian).value"
  conv_factor: "(da * 180 * 3600) / np.pi"
beam:
  fwhm1: "9.735 * da"
  amp1: 0.9808
  fwhm2: "32.627 * da"
  amp2: 0.0192

sim: True

bowling:
  sub_poly: False
  method: "pred2"
  degree: 2
minkasi:
  noise:
    class: "noise.NoiseSmoothedSVD"
    args: "[]"
    kwargs: "{'fwhm':10}"
  maxiter: 20
  npass: 5
  dograd: False
  ntods: 10

models:
  gauss:
    func: "models.derivs_from_gauss_c"
    parameters:
      ps_ra:
        value: "Angle('07 41 44.5 hours').to(u.radian).value"
        to_fit: False
      ps_dec:
        value: "Angle('74:14:38.7 degrees').to(u.radian).value"
        to_fit: False
      sigma:
        value: "1.37e-5"
        to_fit: True
      amp:
        value: "1e-2"
        to_fit: True




