base: "base_sampler.yaml"
name: "RXJ1347"
sim: True
model:
  unit_conversion: "float(mju.get_da(constants['z'])*mju.y2K_RJ(constants['freq'], constants['Te'])*mju.XMpc/mju.me)"
  structures:
    ps_gauss:
      structure: "gaussian"
      parameters:
        dx_g:
          value: 100.25
          to_fit: True
          prior: 'uniform(loc=-200,scale=400)'
        dy_g:
          value: 25.30
          to_fit: True 
          prior: 'uniform(loc=-200,scale=400)'
        sigma:
          value: 10
          to_fit: True
          prior: 'uniform(loc=0,scale=100)'
        amp_g:
          value: 0.01
          to_fit: True 
          prior: 'uniform(loc=0.00,scale=1.00)'
