# Base config to merge into
# If an absolute path is given then it is used
# Otherwise it is assumed to me reative to the directory of this file
base: "MOOJ1142_base.yaml"

# Cluster name
# Used both for the output path as well as to load presets
name: "MOOJ1142"
sim: False # If True use TODs to make noise and add a simulated cluster

paths:
  subdir: "SZ_peak_rs" # Subdirectory to use

coords:
  x0: "(175.6918169*u.degree).to(u.radian).value"
  y0: "(15.4532554*u.degree).to(u.radian).value"

model:
  unit_conversion: "float(wu.get_da(constants['z'])*wu.y2K_RJ(constants['freq'], constants['Te'])*wu.XMpc/wu.me)"
  structures:
    gnfw_rs:
      structure: "gnfw_rs"
      parameters:
        dx_1:
          value: 0.0
          to_fit: True
        dy_1:
          value: 0.0
          to_fit: True
        dz_1:
          value: 0.0
        P0:
          value: 0.103
          to_fit: True
        r_s:
          value: 20.
          to_fit: True
        gamma:
          value: .3081
          to_fit: True
        alpha:
          value: 1.551
          to_fit: True
        beta:
          value: 5.4905
          to_fit: True
        z:
          value: 1.19 
    ps_gauss:
      structure: "gaussian"
      parameters:
        dx_g:
          value: 19.0
          to_fit: True
          priors: [10.0, 28.0]
        dy_g:
          value: -4.0
          to_fit: True
          priors: [-13.0, 5.0]
        sigma:
          value: 4.0
        amp_g:
          value: 0.01
          to_fit: True
