cluster:
  name: "MOO1142"
  Te: 5.0
  freq: 90e9
paths:
  tods: "/scratch/r/rbond/jorlo/M2-TODs/MOOJ1142"
  glob: "Signal_TOD*.fits"
  ndo: False
  odo: False
  outroot: "/scratch/r/rbond/jorlo/Reductions" 
coords:
  z: 1.19 
  r_map: "3.0*60"
  dr: "1."
  x0: 3.06642436 
  y0: 0.26972541 
  conv_factor: "(180 * 3600) / np.pi"
beam:
  fwhm1: "9.735"
  amp1: 0.9808
  fwhm2: "32.627"
  amp2: 0.0192
bowling:
  sub_poly: False
  method: "pred2"
  degree: 2
minkasi:
  noise:
    class: "minkasi.NoiseSmoothedSVD"
    args: "[]"
    kwargs: "{'fwhm':10}"
  maxiter: 50
  npass: 5
  dograd: False
models:
  a10:
    func: "partial(helper, xyz=xyz, dx=float(da*y2K_RJ(freq, Te)*dr[-1]*XMpc/me), beam=beam, argnums=np.where(_to_fit)[0], n_a10=1, n_gaussian = 2)"
    parameters:
      dx_1:
        value: 0.0
        to_fit: True
        priors:
          type: "flat"
          value: "np.array([-9.0, 9.0])"
      dy_1:
        value: 0.0
        to_fit: True
        priors:
          type: "flat"
          value: "np.array([-9.0, 9.0])"
      dz_1:
        value: 0.0
        to_fit: False
      theta:
        value: 0.0
        to_fit: False
      P0:
        value: 8.403
        to_fit: False
      c500:
        value: 1.177
        to_fit: False
      m500:
        value: "5.4e14"
        to_fit: True
      gamma:
        value: .3081
        to_fit: False
      alpha:
        value: 1.051
        to_fit: False
      beta:
        value: 5.4905
        to_fit: False
      z: 
        value: 1.19
        to_fit: False
      dx_g1:
        value: 19.0 
        to_fit: False 
      dy_g1:
        value: 4.3 
        to_fit: False 
      sigma_g1:
        value: 4.0 
        to_fit: False
      amp_g1:
        value: 0.0009485246831922859 
        to_fit: True 
      dx_g2:
        value: 19.0 
        to_fit: False 
      dy_g2:
        value: 4.3 
        to_fit: False 
      sigma_g2:
        value: 4.0 
        to_fit: False
      amp_2:
        value: 0.0009485246831922859 
        to_fit: True 
  
