# Base config to merge into
# If an absolute path is given then it is used
# Otherwise it is assumed to me reative to the directory of this file
base: "MOOJ1142_base.yaml"
model_map: True
# Cluster name
# Used both for the output path as well as to load presets
name: "MOOJ1142"
sim: False

path:
  subdir: "nonpara"

coords:
  x0: "Angle('11 42 47.44 hours').to(u.radian).value" #peak
  y0: "Angle('15:27:13.10 degrees').to(u.radian).value" #peak

# Define the model
model:
  # Unit conversion to apply at the end
  # Will be evaled
  unit_conversion: "float(wu.get_da(constants['z'])*wu.y2K_RJ(constants['freq'], constants['Te'])*wu.XMpc/wu.me)"
  # Structure to include in the model
  structures:
    # Name of the first structure
    nonpara:
    # Name of the first structure
      structure: "nonpara_power"
      n_rbins: 5
      parameters:
        rbins:
          #value: "(0, 30, 60, 90, 120, 180, 300)"
          value: "(0,30,60, 120, 180)"
        amps:
          value: "jnp.array([8.387e5, 4.099e4, 1.233e2, 1.39, 0.0])"
          to_fit: True
        pows:
          value: "jnp.array([-4.27, -3.65, -2.31, -1.01, -4])"
          to_fit: True
        dx_1: # Name of the first parameter
          value: 0.0 # Value to use/start at, will be evaled
          to_fit: False
        dy_1:
          value: 0.0
          to_fit: False
        dz_1:
          value: 0.0
          to_fit: False
        c:
          value: 0
          to_fit: True
    ps_gauss:
      structure: "gaussian"
      parameters:
        dx_g:
          value: 1.838875992189231
          to_fit: True
          priors: [-10.0, 10.0]
        dy_g:
          value: -3.8776721594142134
          to_fit: True
          priors: [-13.0, 5.0]
        sigma:
          value: 5.096751126087345 
        amp_g:
          value: 0.001305594365157566
          to_fit: True
