# Base config to merge into
# If an absolute path is given then it is used
# Otherwise it is assumed to me reative to the directory of this file
base: "MOOJ1142_base.yaml"

# Cluster name
# Used both for the output path as well as to load presets
name: "MOOJ1142"
sim: False # If True use TODs to make noise and add a simulated cluster

paths:
  subdir: "xray_cent_rs" # Subdirectory to use

coords:
  x0: "Angle('11 42 46.82 hours').to(u.radian).value" #centroid
  y0: "Angle('15:27:15.70 degrees').to(u.radian).value" #centroid

model:
  structures:
    gnfw_rs:
      structure: "gnfw_rs"
      parameters:
        dx_1:
          value: 0.0
        dy_1:
          value: 0.0
        dz_1:
          value: 0.0
        P0:
          value: 0.370
          to_fit: True
        r_s:
          value: 20.
          to_fit: True
        gamma:
          value: 0.53
          to_fit: True
          priors: [0.1, 2.0] 
        alpha:
          value: 1.277
          to_fit: True
        beta:
          value: 3.924
          to_fit: True
        z:
          value: 1.19
    ps_gauss:
      structure: "gaussian"
      parameters:
        dx_g:
          value: 1.78
          to_fit: True
        dy_g:
          value: -3.38
          to_fit: True
        sigma:
          value: 4.0
          to_fit: True
        amp_g:
          value: 0.00128582673
          to_fit: True
