# Base config to merge into
# If an absolute path is given then it is used
# Otherwise it is assumed to me reative to the directory of this file
base: "MOOJ1142_base.yaml"

# Cluster name
# Used both for the output path as well as to load presets
name: "MOOJ1142"
sim: False # If True use TODs to make noise and add a simulated cluster

paths:
  subdir: "dwxray_peak" # Subdirectory to use

coords:
  x0: "Angle('11 42 47.44 hours').to(u.radian).value" #peak
  y0: "Angle('15:27:13.10 degrees').to(u.radian).value" #peak

# Define the model
model:
  # Unit conversion to apply at the end
  # Will be evaled
  unit_conversion: "float(wu.get_da(constants['z'])*wu.y2K_RJ(constants['freq'], constants['Te'])*wu.XMpc/wu.me)"
  # Structure to include in the model
  structures:
    # Name of the first structure
    ea10:
      structure: "gnfw" # What type of structure it is

      parameters:
        dx_1: # Name of the first parameter
          value: 0.0 # Value to use/start at, will be evaled
        dy_1:
          value: 0.0
        dz_1:
          value: 0.0
        r1:
          value: 90.0
          to_fit: True
          priors: [0.,300.]
        P0:
          value: 3.202
        c500:
          value: 1.083
        m500:
          value: "8.4e14"
          to_fit: True
        gamma:
          value: 0.3798
          to_fit: True
          priors: [0., 2.] 
        alpha:
          value: 1.4063
        beta:
          value: 5.4905
        z:
          value: 1.19
    ps_gauss:
      structure: "gaussian"
      parameters:
        dx_g:
          value: 1.78
        dy_g:
          value: -3.38
        sigma:
          value: 4.0
        amp_g:
          value: 0.00128582673
