# Base config to merge into
# If an absolute path is given then it is used
# Otherwise it is assumed to me reative to the directory of this file
base: "MOOJ1142_base.yaml"
model_map: True
# Cluster name
# Used both for the output path as well as to load presets
name: "MOOJ1142"
sim: False

path:
  subdir: "nonpara"

coords:
  x0: "Angle('11 42 46.82 hours').to(u.radian).value" #centroid
  y0: "Angle('15:27:15.70 degrees').to(u.radian).value" #centroid

# Define the model
model:
  # Unit conversion to apply at the end
  # Will be evaled
  unit_conversion: "float(wu.get_da(constants['z'])*wu.y2K_RJ(constants['freq'], constants['Te'])*wu.XMpc/wu.me)"
  # Structure to include in the model
  structures:
    # Name of the first structure
    nonpara:
    # Name of the first structure
      structure: "nonpara_power"
      n_rbins: 5
      parameters:
        rbins:
          #value: "(0, 30, 60, 90, 120, 180, 300)"
          value: "(0,30,60, 120, 180)"
        amps:
          value: "jnp.array([5.0, 2., 0.01, 0.01, 0.01])"
          to_fit: True
        pows:
          value: "jnp.array([-0.4, -0.4, -0.4, -1. , -2.5])"
          to_fit: True
        dx_1: # Name of the first parameter
          value: 0.0 # Value to use/start at, will be evaled
          to_fit: False
        dy_1:
          value: 0.0
          to_fit: False
        dz_1:
          value: 0.0
          to_fit: False
        c:
          value: 0
          to_fit: True
        z:
          value: 0.25
          to_fit: False
    ps_gauss:
      structure: "gaussian"
      parameters:
        dx_g:
          value: 19.0
          to_fit: True
          priors: [10.0, 28.0]
        dy_g:
          value: -4.0
          to_fit: True
          priors: [-13.0, 5.0]
        sigma:
          value: 4.0
        amp_g:
          value: 0.1
          to_fit: True
