cluster:
  name: "MS0735"
  Te: 5.0
  freq: 90e9
paths:
  tods: "/scratch/r/rbond/jorlo/MS0735/TS_EaCMS0f0_51_5_Oct_2021"
  glob: "Signal_TOD*.fits"
  ndo: False
  odo: False
  outroot: "/scratch/s/sievers/skh/Reductions"
  subdir: "r3=r1"
coords:
  z: .216
  r_map: "3.0*60*da"
  dr: ".5*da"
  x0: "Angle('07 41 44.5 hours').to(u.radian).value"
  y0: "Angle('74:14:38.7 degrees').to(u.radian).value"
  conv_factor: "(da * 180 * 3600) / np.pi"
beam:
  fwhm1: "9.735 * da"
  amp1: 0.9808
  fwhm2: "32.627 * da"
  amp2: 0.0192
bowling:
  sub_poly: True
  method: "pred2"
  degree: 2
minkasi:
  noise:
    class: "minkasi.NoiseSmoothedSVD"
    args: "[]"
    kwargs: "{'fwhm':10}"
  maxiter: 20
  npass: 5
  dograd: False
models:
  isobeta:
    func: "partial(helper, xyz=xyz, dx=float(y2K_RJ(freq, Te)*dr*XMpc/me), beam=beam, argnums=np.where(_to_fit)[0], n_isobeta=1)"
    parameters:
      dx_1:
        value: 0.0 
        to_fit: False
      dy_1:
        value: 0.0
        to_fit: False
      dz_1:
        value: 0.0 
        to_fit: False
      r_1:
        value: .341
        to_fit: False
      r_2:
        value: .249
        to_fit: False
      r_3:
        value: "params[par_idx['isobeta-r_1']]"
        to_fit: False
      theta_1:
        value: "np.deg2rad(97)"
        to_fit: False
      beta_1:
        value: .98
        to_fit: False
      amp_1:
        value: 0
        to_fit: True
  gauss:
    func: "minkasi.derivs_from_gauss_c"
    parameters:
      ps_ra:
        value: "Angle('07 41 44.5 hours').to(u.radian).value"
        to_fit: False
      ps_dec:
        value: "Angle('74:14:38.7 degrees').to(u.radian).value"
        to_fit: False
      sigma:
        value: "1.37e-5"
        to_fit: True 
      amp:
        value: "1.7e-4"
        to_fit: True 
