cluster:
  name: "MOO_1142"
  Te: 5.0
  freq: 90e9
paths:
  tods: "/scratch/s/sievers/skh/tods/MOO1142/TS_EaCMS0f0_51_16_Feb_2022/"
  glob: "Signal_TOD*.fits"
  ndo: False
  odo: False
  outroot: "/scratch/s/sievers/skh/Reductions"
  subdir: "spherical"
coords:
  z: 1.19 
  r_map: "3.0*60"
  dr: ".5"
  x0: "Angle('11 42 46.6 hours').to(u.radian).value"
  y0: "Angle('15:27:15.0 degrees').to(u.radian).value"
  conv_factor: "(180 * 3600) / np.pi"
beam:
  fwhm1: "9.735"
  amp1: 0.9808
  fwhm2: "32.627"
  amp2: 0.0192
bowling:
  sub_poly: True
  method: "pred2"
  degree: 2
minkasi:
  noise:
    class: "minkasi.NoiseSmoothedSVD"
    args: "[]"
    kwargs: "{'fwhm':10}"
  maxiter: 20
  npass: 5
  dograd: False
models:
  a10:
    func: "partial(helper, xyz=xyz, dx=float(y2K_RJ(freq, Te)*dr*XMpc/me), beam=beam, argnums=np.where(to_fit)[0], re_eval=re_eval, par_idx=par_idx, n_gnfw=1, n_powerlaw=0)"
    parameters:
      dx_1:
        value: 0.0 
        to_fit: False 
      dy_1:
        value: 0.0
        to_fit: False 
      dz_1:
        value: 0.0 
        to_fit: False
      r_1:
        value: 1.0 
        to_fit: False
      r_2:
        value: 1.0 
        to_fit: False
      r_3:
        value: 1.0 
        to_fit: False
      theta:
        value: 0.0 
        to_fit: False
      P0:
        value: 8.403
        to_fit: True 
      c500:
        value: 1.177 
        to_fit: True 
      m500:
        value: "6e14"
        to_fit: True 
      gamma:
        value: .3081 
        to_fit: False
      alpha:
        value: 1.051 
        to_fit: False
      beta:
        value: 5.4905 
        to_fit: False
      z:
        value: 1.19 
        to_fit: False
  gauss:
    func: "minkasi.derivs_from_gauss_c"
    parameters:
      ps_ra:
        value: 3.0665111128123264 
        to_fit: False 
      ps_dec:
        value: 0.2697068189809627 
        to_fit: False 
      sigma:
        value: "1.37e-5"
        to_fit: True 
      amp:
        value: "1.7e-4"
        to_fit: True 
