cluster:
  name: "MOO_1142"
  Te: 5.0
  freq: 90e9
paths:
  tods: "/scratch/s/sievers/skh/tods/MOO1142/TS_EaCMS0f0_51_1_Mar_2023/"
  glob: "Signal_TOD*.fits"
  ndo: False
  odo: False
  outroot: "/scratch/s/sievers/skh/Reductions"
  subdir: "new_tods"
  cut:
    - "Signal_TOD-AGBT18B_215_04-s88.fits"
    - "Signal_TOD-AGBT18B_215_04-s89.fits"
    - "Signal_TOD-AGBT18B_215_04-s91.fits"
    - "Signal_TOD-AGBT18B_215_04-s92.fits"
    - "Signal_TOD-AGBT18B_215_04-s93.fits"
    - "Signal_TOD-AGBT18B_215_04-s94.fits"
coords:
  z: 1.19 
  r_map: "3.0*60"
  dr: ".5"
  x0: 3.0665111128123264 
  y0: 0.2697068189809627 
  conv_factor: "(180 * 3600) / np.pi"
beam:
  fwhm1: "9."
  amp1: 1.0
  fwhm2: "40.0"
  amp2: 0.0192
bowling:
  sub_poly: True
  method: "pred2"
  degree: 2
minkasi:
  noise:
    class: "minkasi.NoiseSmoothedSVD"
    args: "[]"
    kwargs: "{'fwhm':10}"
  maxiter: 50
  npass: 5
  dograd: False
sim: False 
models:
  gauss:
    func: "partial(helper, xyz=xyz, dx=float(dr), beam=beam, argnums=np.where(_to_fit)[0], n_gaussian=2)"
    parameters:
      dx_1:
        value: 0.8
        to_fit: False 
      dy_1:
        value: 1.2 
        to_fit: False 
      dz_1:
        value: 0.0 
        to_fit: False
      r_1:
        value: 0.7 
        to_fit: True 
        priors:
          type: "flat"
          value: "[0.1, 1.0]"
      r_2:
        value: 1.0
        to_fit: False 
      r_3:
        value: 1.0
        to_fit: False 
      theta_1:
        value: .448 
        to_fit: True 
        priors:
          type: "flat"
          value: "[0.0, 2*np.pi]"
      sigma_1:
        value: 2.0 
        to_fit: False
      amp_1:
        value: 0.0009485246831922859 
        to_fit: True
      dx_4:
        value: 0.8
        to_fit: False 
      dy_5:
        value: 1.2 
        to_fit: False 
      dz_6:
        value: 0.0 
        to_fit: False
      r_4:
        value: 0.7 
        to_fit: True 
        priors:
          type: "flat"
          value: "[0.1, 1.0]"
      r_5:
        value: 1.0
        to_fit: False 
      r_6:
        value: 1.0
        to_fit: False 
      theta_2:
        value: .448 
        to_fit: True 
        priors:
          type: "flat"
          value: "[0.0, 2*np.pi]"
      sigma_2:
        value: "9.0/2.355" 
        to_fit: False
        priors:
          type: "flat"
          value: "[7.0/2.355, 11.0/2.355]"
      amp_2:
        value: 0.0009485246831922859 
        to_fit: True
    #func: "minkasi.derivs_from_gauss_c"
    #parameters:
    #  ps_ra:
    #    value: 3.0665111128123264 
    #    to_fit: True 
    #  ps_dec:
    #    value: 0.2697068189809627 
    #    to_fit: True 
    #  sigma:
    #    value: "1.85e-5"
    #    to_fit: True 
    #  amp:
    #    value: "1.7e-4"
    #    to_fit: True 
